export const NATIONALITY_MAP = {
  "Afghan": "Afghanistan",
  "Albanian": "Albania",
  "Algerian": "Algeria",
  "American": "United States",
  "Andorran": "Andorra",
  "Angolan": "Angola",
  "Argentinian": "Argentina",
  "Armenian": "Armenia",
  "Australian": "Australia",
  "Austrian": "Austria",
  "Azerbaijani": "Azerbaijan",
  "Bahamian": "Bahamas",
  "Bahraini": "Bahrain",
  "Bangladeshi": "Bangladesh",
  "Barbadian": "Barbados",
  "Belarusian": "Belarus",
  "Belgian": "Belgium",
  "Belizean": "Belize",
  "Beninese": "Benin",
  "Bhutanese": "Bhutan",
  "Bolivian": "Bolivia",
  "Bosnian": "Bosnia and Herzegovina",
  "Botswanan": "Botswana",
  "Brazilian": "Brazil",
  "British": "United Kingdom",
  "Bruneian": "Brunei",
  "Bulgarian": "Bulgaria",
  "Burkinabe": "Burkina Faso",
  "Burundian": "Burundi",
  "Cambodian": "Cambodia",
  "Cameroonian": "Cameroon",
  "Canadian": "Canada",
  "Cape Verdean": "Cape Verde",
  "Central African": "Central African Republic",
  "Chadian": "Chad",
  "Chilean": "Chile",
  "Chinese": "China",
  "Colombian": "Colombia",
  "Comoran": "Comoros",
  "Congolese": "Congo",
  "Costa Rican": "Costa Rica",
  "Croatian": "Croatia",
  "Cuban": "Cuba",
  "Cypriot": "Cyprus",
  "Czech": "Czech Republic",
  "Danish": "Denmark",
  "Djiboutian": "Djibouti",
  "Dominican": "Dominican Republic",
  "Dutch": "Netherlands",
  "Ecuadorean": "Ecuador",
  "Egyptian": "Egypt",
  "Emirati": "United Arab Emirates",
  "English": "United Kingdom",
  "Equatorial Guinean": "Equatorial Guinea",
  "Eritrean": "Eritrea",
  "Estonian": "Estonia",
  "Ethiopian": "Ethiopia",
  "Fijian": "Fiji",
  "Finnish": "Finland",
  "French": "France",
  "Gabonese": "Gabon",
  "Gambian": "Gambia",
  "Georgian": "Georgia",
  "German": "Germany",
  "Ghanaian": "Ghana",
  "Greek": "Greece",
  "Grenadian": "Grenada",
  "Guatemalan": "Guatemala",
  "Guinean": "Guinea",
  "Guyanese": "Guyana",
  "Haitian": "Haiti",
  "Honduran": "Honduras",
  "Hungarian": "Hungary",
  "Icelander": "Iceland",
  "Indian": "India",
  "Indonesian": "Indonesia",
  "Iranian": "Iran",
  "Iraqi": "Iraq",
  "Irish": "Ireland",
  "Israeli": "Israel",
  "Italian": "Italy",
  "Ivorian": "Ivory Coast",
  "Jamaican": "Jamaica",
  "Japanese": "Japan",
  "Jordanian": "Jordan",
  "Kazakh": "Kazakhstan",
  "Kenyan": "Kenya",
  "Kuwaiti": "Kuwait",
  "Kyrgyz": "Kyrgyzstan",
  "Lao": "Laos",
  "Latvian": "Latvia",
  "Lebanese": "Lebanon",
  "Liberian": "Liberia",
  "Libyan": "Libya",
  "Liechtenstein": "Liechtenstein",
  "Lithuanian": "Lithuania",
  "Luxembourgish": "Luxembourg",
  "Macedonian": "North Macedonia",
  "Malagasy": "Madagascar",
  "Malawian": "Malawi",
  "Malaysian": "Malaysia",
  "Maldivian": "Maldives",
  "Malian": "Mali",
  "Maltese": "Malta",
  "Mauritanian": "Mauritania",
  "Mauritian": "Mauritius",
  "Mexican": "Mexico",
  "Moldovan": "Moldova",
  "Monegasque": "Monaco",
  "Mongolian": "Mongolia",
  "Montenegrin": "Montenegro",
  "Moroccan": "Morocco",
  "Mozambican": "Mozambique",
  "Namibian": "Namibia",
  "Nepalese": "Nepal",
  "New Zealander": "New Zealand",
  "Nicaraguan": "Nicaragua",
  "Nigerian": "Nigeria",
  "Norwegian": "Norway",
  "Omani": "Oman",
  "Pakistani": "Pakistan",
  "Palestinian": "Palestine",
  "Panamanian": "Panama",
  "Papua New Guinean": "Papua New Guinea",
  "Paraguayan": "Paraguay",
  "Peruvian": "Peru",
  "Philippine": "Philippines",
  "Polish": "Poland",
  "Portuguese": "Portugal",
  "Qatari": "Qatar",
  "Romanian": "Romania",
  "Russian": "Russia",
  "Rwandan": "Rwanda",
  "Saint Lucian": "Saint Lucia",
  "Salvadoran": "El Salvador",
  "Samoan": "Samoa",
  "Saudi": "Saudi Arabia",
  "Scottish": "United Kingdom",
  "Senegalese": "Senegal",
  "Serbian": "Serbia",
  "Seychellois": "Seychelles",
  "Sierra Leonean": "Sierra Leone",
  "Singaporean": "Singapore",
  "Slovak": "Slovakia",
  "Slovenian": "Slovenia",
  "Solomon Islander": "Solomon Islands",
  "Somali": "Somalia",
  "South African": "South Africa",
  "South Korean": "South Korea",
  "South Sudanese": "South Sudan",
  "Spanish": "Spain",
  "Sri Lankan": "Sri Lanka",
  "Sudanese": "Sudan",
  "Surinamer": "Suriname",
  "Swazi": "Eswatini",
  "Swedish": "Sweden",
  "Swiss": "Switzerland",
  "Syrian": "Syria",
  "Taiwanese": "Taiwan",
  "Tajik": "Tajikistan",
  "Tanzanian": "Tanzania",
  "Thai": "Thailand",
  "Togolese": "Togo",
  "Tongan": "Tonga",
  "Trinidadian": "Trinidad and Tobago",
  "Tunisian": "Tunisia",
  "Turkish": "Turkey",
  "Turkmen": "Turkmenistan",
  "Ugandan": "Uganda",
  "Ukrainian": "Ukraine",
  "Uruguayan": "Uruguay",
  "Uzbek": "Uzbekistan",
  "Venezuelan": "Venezuela",
  "Vietnamese": "Vietnam",
  "Yemeni": "Yemen",
  "Zambian": "Zambia",
  "Zimbabwean": "Zimbabwe"
};

